### ISSUE TITLE
‎

### ISSUE THREAD

**Issue by ShivaShirsath** [oscarkarnalim/strange#2]
How to run this in Ubuntu 20.04 aarch64 
In Android Studio or in vs code ?

**Comment by oscarkarnalim** [comment]
Hi  Shiva Shirsath,

I wrote the program with Eclipse so if you need to edit it from other IDEs, I presume you need to migrate the code and the libraries manually. It is easier to open it with Eclipse again though.

If you only want to run the program, you can use command prompt, run the JAR file (download the released version), and follow the instructions in STRANGE homepage: https://github.com/oscarkarnalim/strange

Thank you!

**Comment by ShivaShirsath** [comment]
Thank you for responding.

I see your published pepar and i am curious to run it.
